typography_spectrum: 0.26488
color:
  brandColors:
    - '#080808'
    - '#272823'
    - '#6f5f37'
    - '#aaa9a7'
    - '#e7f0d5'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: 99website
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: WE MAKE BEAUTIFUL WEBSITES
description: FOR £99!
purpose: []
